name: Release
on: workflow_dispatch

permissions: write-all

jobs:
  build-android:
    uses: ./.github/workflows/android-build.yml
  build-ios:
    uses: ./.github/workflows/ios_build.yml

  Releaser:
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    steps:
      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
          name: Paper-Lily
          path: ${{ github.workspace }}

      - name: Move Android File
        run: mv "${{ github.workspace }}/Paper-Lily.apk" "${{ github.workspace }}/Paper-Lily-Android.apk"

      - name: Download iOS Build
        uses: actions/download-artifact@main
        with:
          name: Paper-Lily
          path: ${{ github.workspace }}

      - name: Move iOS File
        run: mv "${{ github.workspace }}build/Paper-Lily.ipa" "${{ github.workspace }}PaperLily-iOS.ipa"

      - name: Get next tag
        id: tag
        run: |
          git fetch --tags
          latest=$(git tag -l "beta-*" | sort -V | tail -n 1)

          if [ -z "$latest" ]; then
            next="beta-0.0.6"
          else
            version=${latest#beta-}
            IFS='.' read -r major minor patch <<< "$version"
            patch=$((patch+1))
          next="beta-$major.$minor.$patch"
          fi

              echo "tag=$next" >> $GITHUB_OUTPUT

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "beta-v0"
          tag_name: "beta-0.0.5"
          prerelease: true
          files: |
            ${{ github.workspace }}/Paper-Lily-Android.apk
            ${{ github.workspace }}/Paper-Lily-iOS.ipa
