name: Release
on: workflow_dispatch

permissions: write-all

jobs:
  build-android:
    uses: ./.github/workflows/android-build.yml
  #build-ios:
    #uses: ./.github/workflows/ios_build.yml

  Releaser:
    needs: [build-android]
    runs-on: ubuntu-latest
    steps:
      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
          name: Paper-Lily
          path: ${{ github.workspace }}

      - name: Move Android File
        run: mv "${{ github.workspace }}/Paper-Lily.apk" "${{ github.workspace }}/Paper-Lily-Android.apk"

      #- name: Download iOS Build
        #uses: actions/download-artifact@main
       # with:
         # name: Codename Engine iOS
         # path: ${{ github.workspace }}

      #- name: Move iOS File
       # run: mv "${{ github.workspace }}build/*.ipa" "${{ github.workspace }}build/PaperLily-iOS.ipa"

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "release-v1"
          tag_name: "beta-v1.5.6"
          prerelease: false
          files: |
            ${{ github.workspace }}/Paper-Lily-Android.apk
       #     ${{ github.workspace }}/*.ipa
